## host to bind, can also be passed via CLI args
host = "ATUIN_HOST"

## port to bind, can also be passed via CLI args
port = ATUIN_PORT

## whether to allow anyone to register an account
open_registration = ATUIN_OPEN_REGISTRATION

## URI for postgres (using development creds here)
db_uri="ATUIN_DB_URI"

## Maximum size for one history entry
# max_history_length = 8192

## Maximum size for one record entry
## 1024 * 1024 * 1024
# max_record_size = 1073741824

## Webhook to be called when user registers on the servers
# register_webhook_username = ""

## Default page size for requests
page_size = ATUIN_PAGE_SIZE

# [metrics]
# enable = false
# host = 127.0.0.1
# port = 9001

# [tls]
# enable = false
# cert_path = ""
# pkey_path = ""